name: Build and Push Workflow

on:
  push:
    branches:
      - master

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Run Build
      run: npm run build

    - name: Set deployment token
      run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
      
    - name: Deploy to NPM
      run: npm publish
