name: Build and Push Workflow

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Run Build
      run: npm run build

    - name: Run Push
      run: npm run push
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
